ChatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('public_chat.urls', namespace='public_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='private_chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from .views import private_chat_room_view, create_or_return_private_chat

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private-chat-room'),
    path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('chat.urls', namespace='private_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('public', include('public_chat.urls', namespace='public_chat')),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

public_chat/urls.py
from django.urls import path

from .views import home_screen_view, create_public_chat

app_name = 'chat'

urlpatterns = [
    path('', home_screen_view, name='public_chat_view'),
    path('create_public_chat/', create_public_chat, name='create_public_chat'),
]

templates/components/navbar/nav-chat-notification.html
<!-- Notifications - Notices -->
<div class="tab-pane fade h-100
{% if not groups or not m_and_f %}
show active
{% endif %}" id="tab-content-notifications" role="tabpanel">
    <div class="d-flex flex-column h-100">
        <div class="hide-scrollbar">
            <div class="container py-8">

                <!-- Title -->
                <div class="d-flex justify-content-between mb-8">
                    <h2 class="fw-bold m-0">Notifications</h2>
                    <a class="icon icon-lg text-muted d-xl-none my-auto me-6" href="#"
                       onclick="toggleMainClass()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                             stroke-linejoin="round" class="feather feather-chevron-right">
                            <polyline points="9 18 15 12 9 6"></polyline>
                        </svg>
                    </a>
                </div>

                <!-- Search -->
                {% include 'components/navbar/nav-search.html' %}


                <!-- Notifications -->
                <div class="card-list mt-8" id="id_chat_notifications_container">


                </div>

            </div>
        </div>
    </div>
</div>

<div class="toast-container position-absolute p-5 bottom-0 end-0" style="z-index: 99"
     id="id_chat_notification_toast_container">
</div>

<script type="text/javascript">
    /*
        Sets the scroll listener for when user scrolls to bottom of notification menu.
        It will retrieve the next page of results.
    */
    function setOnChatNotificationScrollListener() {
        var menu = document.getElementById("id_chat_notifications_container")
        if (menu != null) {
            menu.addEventListener("scroll", function (e) {

                if ((menu.scrollTop) >= (menu.scrollHeight - menu.offsetHeight)) {
                    getNextChatNotificationsPage()
                }
            });
        }

    }

    setOnChatNotificationScrollListener()

</script>

templates/components/navbar/nav-chat.html
{% load static %}
<!-- Chats -->
<div class="tab-pane fade h-100
{% if m_and_f %}
show active
{% endif %}" id="tab-content-chats" role="tabpanel">
    <div class="d-flex flex-column h-100 position-relative">
        <div class="hide-scrollbar">

            <div class="container py-8">
                <!-- Title -->
                <div class="d-flex justify-content-between mb-8">
                    <h2 class="fw-bold m-0">Chats</h2>
                    <a class="icon icon-lg text-muted d-xl-none my-auto me-6" href="#"
                       onclick="toggleMainClass()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                             stroke-linejoin="round" class="feather feather-chevron-right">
                            <polyline points="9 18 15 12 9 6"></polyline>
                        </svg>
                    </a>
                </div>

                <!-- Search -->
                {% include 'components/navbar/nav-search.html' %}

                <!-- Chats -->
                <div class="card-list">
                    {% if m_and_f %}
                        {% for x in m_and_f %}
                            <!-- Card -->
                            <div class="card border-0 text-reset" onclick="onSelectFriend('{{ x.friend.id }}')"
                                 id="id_friend_container_{{ x.friend.id }}">
                                <div class="card-body">
                                    <div class="row gx-5">
                                        <div class="col-auto">
                                            <div class="avatar">
                                                <img src="{% static 'img/dummy_image.png' %}" alt="#" class="avatar-img"
                                                     id="id_friend_img_{{ x.friend.id }}">
                                            </div>
                                        </div>

                                        <div class="col">
                                            <div class="d-flex align-items-center mb-3">
                                                <h5 class="me-auto mb-0">{{ x.friend.username|truncatechars:14 }}</h5>
                                                <span class="text-muted extra-small ms-2">{{ x.message.timestamp|timesince }} ago</span>
                                            </div>

                                            <div class="d-flex align-items-center">
                                                <div class="line-clamp me-auto">
                                                    {% if x.message.user.id == request.user.id %}
                                                        You: {{ x.message|truncatechars:30 }}
                                                    {% else %}
                                                        {{ x.message|truncatechars:30 }}
                                                    {% endif %}

                                                </div>

                                                {#                                            <div class="badge badge-circle bg-primary ms-5">#}
                                                {#                                                <span>3</span>#}
                                                {#                                            </div>#}
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .card-body -->
                            </div>
                            <!-- Card -->
                        {% endfor %}
                    {% else %}
                        <div class="card border-0 text-reset">
                            <div class="card-body text-center">
                                <h4 class="text-muted mb-1">Sorry! Try Adding Friends to start a new Chat.
                                </h4>
                            </div>
                        </div>
                    {% endif %}
                </div>

                <!-- Chats -->
            </div>

        </div>
    </div>
</div>

templates/components/navbar/nav-general-notification.html
<!-- Friends -->
<div class="tab-pane fade h-100" id="tab-content-friends" role="tabpanel">
    <div class="d-flex flex-column h-100">
        <div class="hide-scrollbar">
            <div class="container py-8">

                <!-- Title -->
                <div class="d-flex justify-content-between mb-8">
                    <h2 class="fw-bold m-0">Friends</h2>
                    <a class="icon icon-lg text-muted d-xl-none my-auto me-6" href="#"
                       onclick="toggleMainClass()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                             stroke-linejoin="round" class="feather feather-chevron-right">
                            <polyline points="9 18 15 12 9 6"></polyline>
                        </svg>
                    </a>
                </div>

                <!-- Search -->
                {% include 'components/navbar/nav-search.html' %}



                <!-- Notifications -->
                <div class="card-list mt-8" id="id_general_notifications_container">

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    /*
        Sets the scroll listener for when user scrolls to bottom of notification menu.
        It will retrieve the next page of results.
    */
    function setOnGeneralNotificationScrollListener() {
        var menu = document.getElementById("id_general_notifications_container")
        if (menu != null) {
            menu.addEventListener("scroll", function (e) {
                if ((menu.scrollTop) >= (menu.scrollHeight - menu.offsetHeight)) {
                    getNextGeneralNotificationsPage()
                }
            })
        }
    }

    setOnGeneralNotificationScrollListener()
</script>

templates/components/navbar/nav-public-chat.html
{% load static %}
<!-- Chats -->
<div class="tab-pane fade h-100
{% if groups %}
show active
{% endif %}" id="tab-content-public-channels" role="tabpanel">
    <div class="d-flex flex-column h-100 position-relative">
        <div class="hide-scrollbar">

            <div class="container py-8">
                <!-- Title -->
                <div class="d-flex justify-content-between mb-8">
                    <h2 class="fw-bold m-0">Public Channels</h2>
                    <a class="icon icon-lg text-muted d-xl-none my-auto me-6" href="#"
                       onclick="toggleMainClass()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                             stroke-linejoin="round" class="feather feather-chevron-right">
                            <polyline points="9 18 15 12 9 6"></polyline>
                        </svg>
                    </a>
                </div>

                <!-- Search -->
                {% include 'components/navbar/nav-search.html' %}


                <!-- Chats -->
                <div class="card-list">
                    {% for group in groups %}
                        <!-- Card -->
                        <div class="card border-0 text-reset" onclick="onSelectGroup('{{ group.room.id }}')"
                             id="id_group_container_{{ group.room.id }}">
                            <div class="card-body">
                                <div class="row gx-5">
                                    <div class="col-auto">
                                        <div class="avatar">
                                            <img src="{% static 'img/dummy_image.png' %}" alt="#" class="avatar-img"
                                                 id="id_group_img_{{ group.room.id }}">
                                        </div>
                                    </div>

                                    <div class="col">
                                        <div class="d-flex align-items-center mb-3">
                                            <h5 class="me-auto mb-0">{{ group.room.title|truncatechars:35 }}</h5>
                                            <span class="text-muted extra-small ms-2">{{ group.message.timestamp|timesince }} ago</span>
                                        </div>

                                        <div class="d-flex align-items-center">
                                            <div class="line-clamp me-auto">
                                                {% if group.message.user.id == request.user.id %}
                                                    You: {{ group.message|truncatechars:30 }}
                                                {% else %}
                                                    {{ group.message|truncatechars:30 }}
                                                {% endif %}
                                            </div>

                                            {#                                            <div class="badge badge-circle bg-primary ms-5">#}
                                            {#                                                <span>3</span>#}
                                            {#                                            </div>#}
                                        </div>
                                    </div>
                                </div>
                            </div><!-- .card-body -->
                        </div>
                        <!-- Card -->
                    {% endfor %}
                </div>

                <!-- Chats -->
            </div>

        </div>
    </div>
</div>

templates/components/navbar/nav-search.html
<div class="mb-6">
    <form onsubmit="return executeQuery();">
        <div class="input-group">
            <div class="input-group-text">
                <div class="icon icon-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round" class="feather feather-search">
                        <circle cx="11" cy="11" r="8"></circle>
                        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                    </svg>
                </div>
            </div>

            <input type="text" class="search-box form-control form-control-lg ps-0"
                   placeholder="Search for users" aria-label="Search for users..." name="q">
        </div>
    </form>
</div>

templates/components/navbar/navbar.html
<nav class="navigation d-flex flex-column text-center navbar navbar-light hide-scrollbar">
    <!-- Brand -->
    <a href="{% url 'public_chat:public_chat_view' %}" title="Messenger" class="d-none d-xl-block mb-6">
        <svg version="1.1" width="46px" height="46px" fill="currentColor" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 46 46"
             enable-background="new 0 0 46 46" xml:space="preserve">
            <polygon opacity="0.7" points="45,11 36,11 35.5,1 "/>
            <polygon points="35.5,1 25.4,14.1 39,21 "/>
            <polygon opacity="0.4" points="17,9.8 39,21 17,26 "/>
            <polygon opacity="0.7" points="2,12 17,26 17,9.8 "/>
            <polygon opacity="0.7" points="17,26 39,21 28,36 "/>
            <polygon points="28,36 4.5,44 17,26 "/>
            <polygon points="17,26 1,26 10.8,20.1 "/>
        </svg>

    </a>

    <!-- Nav items -->
    <ul class="d-flex nav navbar-nav flex-row flex-xl-column flex-grow-1 justify-content-between justify-content-xl-center align-items-center w-100 py-4 py-lg-2 px-lg-3"
        role="tablist">
        <!-- Invisible item to center nav vertically -->
        <li class="nav-item d-none d-xl-block invisible flex-xl-grow-1">
            <a class="nav-link py-0 py-lg-8" href="#" title="">
                <div class="icon icon-xl">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-x">
                        <line x1="18" y1="6" x2="6" y2="18"></line>
                        <line x1="6" y1="6" x2="18" y2="18"></line>
                    </svg>
                </div>
            </a>
        </li>

        <!-- Public Channesl -->
        <li class="nav-item">
            <a class="nav-link py-0 py-lg-8
                {% if groups %}
                active
                {% endif %}" id="tab-public-channels" href="#tab-content-public-channels"
               title="Public Channels"
               data-bs-toggle="tab" role="tab">
                <div class="icon icon-xl">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-hash">
                        <line x1="4" y1="9" x2="20" y2="9"></line>
                        <line x1="4" y1="15" x2="20" y2="15"></line>
                        <line x1="10" y1="3" x2="8" y2="21"></line>
                        <line x1="16" y1="3" x2="14" y2="21"></line>
                    </svg>
                </div>
            </a>
        </li>

        <!-- Friends -->
        <li class="nav-item" onclick="setGeneralNotificationsAsRead()">
            <a class="nav-link py-0 py-lg-8" id="tab-friends" href="#tab-content-friends" title="Friends"
               data-bs-toggle="tab" role="tab">
                <div class="icon icon-xl" id="id_general_notifications_count">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-users">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                    </svg>
                    <div id="id_general_notifications_div">
                        <span id="id_general_notifications_span"></span>
                    </div>
                </div>
            </a>
        </li>

        <!-- Notification -->
        <li class="nav-item">
            <a class="nav-link
             {% if not groups and not m_and_f %}
             active
             {% endif %}py-0 py-lg-8" id="tab-notifications" href="#tab-content-notifications"
               title="Notifications" data-bs-toggle="tab" role="tab">
                <div class="icon icon-xl" id="id_chat_notifications_count">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-bell">
                        <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                        <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                    </svg>
                    <div id="id_chat_notifications_div">
                        <span id="id_chat_notifications_span"></span>
                    </div>
                </div>
            </a>
        </li>


        <!-- Chats -->
        <li class="nav-item">
            <a class="nav-link py-0 py-lg-8
                {% if m_and_f %}
                active
                {% endif %}" id="tab-chats" href="#tab-content-chats" title="Chats"
               data-bs-toggle="tab" role="tab">
                <div class="icon icon-xl">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-message-square">
                        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                    </svg>
                </div>
            </a>

        </li>

        <!-- Settings -->
        <li class="nav-item d-none d-xl-block flex-xl-grow-1">
            {#            <a class="nav-link py-0 py-lg-8" id="tab-settings" href="#tab-content-settings" title="Settings"#}
            {#               data-bs-toggle="tab" role="tab">#}
            {#                <div class="icon icon-xl">#}
            {#                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"#}
            {#                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"#}
            {#                         class="feather feather-settings">#}
            {#                        <circle cx="12" cy="12" r="3"></circle>#}
            {#                        <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>#}
            {#                    </svg>#}
            {#                </div>#}
            {#            </a>#}
        </li>

        <!-- Dark Mode -->
        <li class="nav-item d-none d-xl-block" id="id_dark_mode_btn">
            <input class="d-none" type="button" id="id_dark_mode_value" value="ON">
            <a class="nav-link py-0 py-lg-8" href="#" title="Dark Mode">
                <div class="icon icon-xl">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-moon">
                        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
                    </svg>
                </div>
            </a>
        </li>

        <!-- Profile -->
        <li class="nav-item">
            <a href="#" class="nav-link p-0 mt-lg-2" data-bs-toggle="modal" data-bs-target="#modal-profile">
                <div class="avatar avatar-online mx-auto d-none d-xl-block">
                    <img class="avatar-img" src="{{ request.user.profile_image.url }}">
                </div>
                <div class="avatar avatar-online avatar-xs d-xl-none">
                    <img class="avatar-img" src="{{ request.user.profile_image.url }}">

                </div>
            </a>
        </li>
    </ul>
</nav>
<!-- Navigation -->

<!-- JavaScript -->
{% include 'components/general_notifications.html' %}
{% include 'components/chat_notifications.html' %}

<!-- Setup SOCKET for NOTIFICATIONS -->
<script type="text/javascript">
    // Correctly decide between ws:// and wss://
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    var ws_path = ws_scheme + '://' + window.location.host + ":8001/"; // PRODUCTION
    // var ws_path = ws_scheme + '://' + window.location.host + "/";
    // console.log("Connecting to " + ws_path);
    var notificationSocket = new WebSocket(ws_path);

    // Handle incoming messages
    notificationSocket.onmessage = function (message) {
        console.log("Got notification websocket message. ")
        var data = JSON.parse(message.data);

        /*
            GENERAL NOTIFICATIONS
        */
        // new 'general' notifications data payload
        if (data.general_msg_type == 0) {
            handleGeneralNotificationsData(data['notifications'], data['new_page_number'])
        }

        if (data.general_msg_type == 1) {
            setGeneralPaginationExhausted()
        }

        if (data.general_msg_type == 2) {
            refreshGeneralNotificationsData(data['notifications'])
        }

        if (data.general_msg_type == 3) {
            handleNewGeneralNotificationsData(data['notifications'])
        }

        if (data.general_msg_type == 4) {
            setUnreadGeneralNotificationsCount(data['count'])
        }

        if (data.general_msg_type == 5) {
            updateGeneralNotificationDiv(data['notification'])
        }

        /*
            CHAT NOTIFICATIONS
        */

        // new 'chat' notifications data payload
        if (data.chat_msg_type == 10) {
            handleChatNotificationsData(data['notifications'], data['new_page_number'])
        }

        // "Chat" Pagination exhausted. No more results.
        if (data.chat_msg_type == 11) {
            setChatPaginationExhausted()
        }

        // refreshed chat notifications
        if (data.chat_msg_type == 13) {
            handleNewChatNotificationsData(data['notifications'])
        }

        if (data.chat_msg_type == 14) {
            setChatNotificationsCount(data['count'])
        }
    }

    notificationSocket.onclose = function (e) {
        console.error('Notification Socket closed unexpectedly');
    };

    notificationSocket.onopen = function (e) {
        console.log("Notification Socket on open: " + e)
        setupGeneralNotificationsMenu()
        getFirstGeneralNotificationsPage()
        getUnreadGeneralNotificationsCount()

        setupChatNotificationsMenu()
        getFirstChatNotificationsPage()
    }

    notificationSocket.onerror = function (e) {
        console.log('Notification Socket error', e)
    }

    if (notificationSocket.readyState == WebSocket.OPEN) {
        console.log("Notification Socket OPEN complete.")
    } else if (notificationSocket.readyState == WebSocket.CONNECTING) {
        console.log("Notification Socket connecting..")
    }
</script>

<script type="text/javascript">
    document.getElementById("tab-public-channels").addEventListener("click", function (e) {
        window.location.href = "{% url 'public_chat:public_chat_view' %}"

    })

    document.getElementById("tab-chats").addEventListener("click", function (e) {
        window.location.href = "{% url 'private_chat:private-chat-room' %}"

    })


    function executeQuery() {
        var queries = document.querySelectorAll('.search-box');

        for (i = 0; i < queries.length; i++) {
            query = queries[i].value
            if (query != "") {
                window.location.replace("{% url 'search' %}?q=" + query)
            }
        }

        return false
    }


    function toggleMainClass() {
        var mainDiv = document.querySelector(".main")
        mainDiv.classList.toggle("is-visible")
    }
</script>
<!-- JavaScript -->