ChatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('public_chat.urls', namespace='public_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='private_chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from .views import private_chat_room_view, create_or_return_private_chat

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private-chat-room'),
    path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('chat.urls', namespace='private_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('public', include('public_chat.urls', namespace='public_chat')),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

public_chat/urls.py
from django.urls import path

from .views import home_screen_view, create_public_chat

app_name = 'chat'

urlpatterns = [
    path('', home_screen_view, name='public_chat_view'),
    path('create_public_chat/', create_public_chat, name='create_public_chat'),
]

account/forms.py
import email
from attr import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2',)

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")


class DateInput(forms.DateInput):
    input_type = 'date'


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_info', 'hide_friends', 'first_name', 'last_name', 'bio',
                  'birth_date')
        widgets = {
            'birth_date': DateInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} is already in use.')

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError(f'Username  is {username} already in use.')

    def save(self, commit=True):
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email']
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_info = self.cleaned_data['hide_info']
        if commit:
            account.save()
        return account

templates/password_reset/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Head -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover">
    <title>{% block title %}ChatApp{% endblock title %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">


    <!-- Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700" rel="stylesheet">

    <!-- Local Js & CSS -->
    <link rel="stylesheet" href="{% static 'css/style.light.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.dark.css' %}" media="(prefers-color-scheme: dark)">
    <script src="{% static 'js/template.js' %}"></script>
    <script src="{% static 'js/vendor.js' %}"></script>
</head>
<body class="bg-light">
{% block content %}

{% endblock content %}
</body>

</html>

templates/password_reset/password_change.html
{% extends 'password_reset/auth_base.html' %}
{% block title %}Signup{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row align-items-center justify-content-center min-vh-100 gx-0">
            <div class="col-12 col-md-5 col-lg-4">
                <div class="card card-shadow border-0">
                    <div class="card-body">
                        <form class="row g-6" method="post">
                            {% csrf_token %}
                            <div class="col-12">
                                <div class="text-center">
                                    <h3 class="fw-bold mb-2">Change Password</h3>
                                    <p>Follow the easy steps</p>
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-floating">
                                    <input name="old_password"
                                            {% if form.errors.old_password %}
                                           class="form-control is-invalid"
                                            {% else %}
                                           class="form-control"
                                            {% endif %}
                                           placeholder="Old Password"
                                           type="password" id="id_old_password" required autofocus>
                                    <label for="id_old_password">Old Password</label>
                                    {% if form.errors.old_password %}
                                        <div id="id_input_first_name" class="invalid-feedback">
                                            <p>{{ form.errors.old_password|striptags }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-floating">
                                    <input name="new_password1"
                                            {% if form.errors.new_password1 %}
                                           class="form-control is-invalid"
                                            {% else %}
                                           class="form-control"
                                            {% endif %}
                                           placeholder="New Password"
                                           type="password" id="id_new_password1" required>
                                    <label for="id_new_password1">New Password</label>
                                    {% if form.errors.new_password1 %}
                                        <div id="id_input_first_name" class="invalid-feedback">
                                            <p>{{ form.errors.new_password1|striptags }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-floating">
                                    <input name="new_password2"
                                            {% if form.errors.new_password2 %}
                                           class="form-control is-invalid"
                                            {% else %}
                                           class="form-control"
                                            {% endif %}
                                           placeholder="Confirm Password"
                                           type="password" id="id_new_password2" required>
                                    <label for="id_new_password2">Confirm Password</label>
                                    {% if form.errors.new_password2 %}
                                        <div id="id_input_first_name" class="invalid-feedback">
                                            <p>{{ form.errors.new_password2|striptags }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            {% if form.non_field_errors %}
                                <p class="text-danger">{{ form.non_field_errors }}</p>
                            {% endif %}


                            <button class="btn btn-lg btn-primary btn-block" type="submit">Change Password</button>

                        </form>
                    </div>
                </div>

                <!-- Text -->
                <div class="text-center mt-8">
                    <p>Go back to <a href="{% url 'public_chat:public_chat_view' %}">Home Page ⏩</a></p>
                </div>

            </div>
        </div>
    </div>


{% endblock content %}

templates/password_reset/password_change_done.html
{% extends 'password_reset/auth_base.html' %}

{% block content %}
    <div class="container">
        <div class="row align-items-center justify-content-center min-vh-100 gx-0">

            <div class="col-12 col-md-9 ">
                <div class="card card-shadow border-0">
                    <div class="card-body">
                        <div class="row g-6">
                            <div class="col-12">
                                <div class="text-center">
                                    <h3 class="fw-bold mb-2">Your password has been Updated ✅</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Text -->
                <div class="text-center mt-8">
                    <p class="m-auto p-2"><a href="{% url 'homepage' %}">Return to Home Page ⏩</a></p>
                </div>
            </div>
        </div> <!-- / .row -->
    </div>
{% endblock content %}

templates/password_reset/password_reset_complete.html
{% extends 'password_reset/auth_base.html' %}

{% block content %}
    <div class="container">
        <div class="row align-items-center justify-content-center min-vh-100 gx-0">

            <div class="col-12 col-md-9 ">
                <div class="card card-shadow border-0">
                    <div class="card-body">
                        <div class="row g-6">
                            <div class="col-12">
                                <div class="text-center">
                                    <h3 class="fw-bold mb-2">Your password has been reset ✅</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Text -->
                <div class="text-center mt-8">
                    <p class="m-auto p-2">You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
                </div>
            </div>
        </div> <!-- / .row -->
    </div>
{% endblock content %}

templates/password_reset/password_reset_done.html
{% extends 'password_reset/auth_base.html' %}

{% block content %}
    <div class="container">
        <div class="row align-items-center justify-content-center min-vh-100 gx-0">

            <div class="col-12 col-md-9 ">
                <div class="card card-shadow border-0">
                    <div class="card-body">
                        <div class="row g-6">
                            <div class="col-12">
                                <div class="text-center">
                                    <h3 class="fw-bold mb-2">Done ✅</h3>
                                    <p> We've emailed you instructions for setting your password, if an account exists
                                        with the email you
                                        entered.
                                        You should receive them shortly.</p>
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="text-center">
                                    <p> If you don't receive an email, please make sure you've entered the address you
                                        registered with,
                                        and check your spam folder.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Text -->
                <div class="text-center mt-8">
                    <p class="m-auto p-2"><a href="{% url 'login' %}">Return to Login Page ⏩</a></p>

                </div>
            </div>
        </div> <!-- / .row -->
    </div>
{% endblock content %}

templates/password_reset/password_reset_email.html
{% autoescape off %}
    To initiate the password reset process for your Account {{ user.email }},
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser
    window instead.

    Sincerely,
    The Open-Chat Team
{% endautoescape %}

templates/password_reset/password_reset_form.html
{% extends 'password_reset/auth_base.html' %}

{% if validlink %}

    {% block content %}

        <div class="container">
            <div class="row align-items-center justify-content-center min-vh-100 gx-0">

                <div class="col-12 col-md-5 col-lg-4">
                    <div class="card card-shadow border-0">
                        <div class="card-body">
                            <form method="POST" class="row g-6">
                                {% csrf_token %}
                                <div class="col-12">
                                    <div class="text-center">
                                        <h3 class="fw-bold mb-2">Password Reset</h3>
                                        <p>Please enter your new password twice</p>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating">
                                        <input name="email" type="email"
                                                {% if form.errors.email %}
                                               class="form-control is-invalid"
                                                {% else %}
                                               class="form-control"
                                                {% endif %}
                                               id="id_input_email"
                                               placeholder="Email address" required="true" autocomplete="username"
                                               value="{{ form.user.get_username }}">
                                        <label for="id_input_email">Email</label>
                                        {% if form.errors.email %}
                                            <div id="id_input_email" class="invalid-feedback">
                                                <p>{{ form.errors.email|striptags }}</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating">
                                        <input type="password"
                                                {% if form.errors.new_password1 %}
                                               class="form-control is-invalid"
                                                {% else %}
                                               class="form-control"
                                                {% endif %}
                                               name="new_password1"
                                               autocomplete="new-password" placeholder="Password" required
                                               id="id_new_password1">
                                        <label for="id_new_password1">Password</label>
                                        {% if form.errors.new_password1 %}
                                            <div id="id_new_password1" class="invalid-feedback">
                                                <p>{{ form.errors.new_password1|striptags }}</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating">
                                        <input type="password"
                                                {% if form.errors.new_password2 %}
                                               class="form-control is-invalid"
                                                {% else %}
                                               class="form-control"
                                                {% endif %}
                                               name="new_password2"
                                               autocomplete="new-password" placeholder="Confirm Password" required
                                               id="id_new_password2">
                                        <label for="id_new_password2">Confirm Password</label>
                                        {% if form.errors.new_password2 %}
                                            <div id="id_new_password1" class="invalid-feedback">
                                                <p>{{ form.errors.new_password2|striptags }}</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>

                                {% if form.non_field_errors %}
                                    <p class="text-danger">{{ form.non_field_errors|striptags }}</p>
                                {% endif %}

                                <div class="col-12">
                                    <button class="btn btn-block btn-lg btn-primary w-100"
                                            type="submit">
                                        Change my password
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Text -->
                    <div class="text-center mt-8">
                        <p>Already have an account? <a href="{% url 'login' %}">Sign in</a></p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}


{% else %}

    <p>The password reset link was invalid, possibly because it has already been used. Please request a new password
        reset.</p>

{% endif %}

templates/password_reset/password_reset_link.html
{% extends 'password_reset/auth_base.html' %}
{% block content %}

    <div class="container">
        <div class="row align-items-center justify-content-center min-vh-100 gx-0">

            <div class="col-12 col-md-5 col-lg-4">
                <div class="card card-shadow border-0">
                    <div class="card-body">
                        <form id="id_password_reset_form" method="POST" class="row g-6">
                            {% csrf_token %}
                            <div class="col-12">
                                <div class="text-center">
                                    <h3 class="fw-bold mb-2">Password Reset</h3>
                                    <p>Enter your email to reset password</p>
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-floating">
                                    <input name="email" type="email"
                                            {% if form.errors.email %}
                                           class="form-control is-invalid"
                                            {% else %}
                                           class="form-control"
                                            {% endif %}
                                           id="id_email"
                                           placeholder="Email address" required>
                                    <label for="id_email">Email</label>
                                    {% if form.errors.email %}
                                        <div id="id_input_email" class="invalid-feedback">
                                            <p>{{ form.errors.email|striptags }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            {% if form.non_field_errors %}
                                <p class="text-danger">{{ form.non_field_errors|striptags }}</p>
                            {% endif %}

                            <div class="col-12">
                                <button id="id_submit_btn" class="btn btn-block btn-lg btn-primary w-100" type="submit">
                                    Send Reset Email
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Text -->
                <div class="text-center mt-8">
                    <p>Already have an account? <a href="{% url 'login' %}">Sign in</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}