ChatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('public_chat.urls', namespace='public_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='private_chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from .views import account_view, edit_account_view, crop_image

app_name = 'account'

urlpatterns = [

    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    path('<user_id>/edit/cropImage/', crop_image, name="crop_image"),

]

chat/urls.py
from django.urls import path

from .views import private_chat_room_view, create_or_return_private_chat

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private-chat-room'),
    path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from account.views import register_view, login_view, logout_view, account_search_view

urlpatterns = [
    path('', include('chat.urls', namespace='private_chat')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('public', include('public_chat.urls', namespace='public_chat')),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_link.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone

from notification.models import Notification


# Create your models here.

class PrivateChatRoom(models.Model):
    # A private room for people to chat in.

    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user1")
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user2")

    # Users who are currently connected to the socket (Used to keep track of unread messages)
    connected_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="connected_users")
    is_active = models.BooleanField(default=False)

    def connect_user(self, user):
        """
		return true if user is added to the connected_users list
		"""
        is_user_added = False
        if not user in self.connected_users.all():
            self.connected_users.add(user)
            is_user_added = True
        return is_user_added

    def disconnect_user(self, user):
        """
	    return true if user is removed from connected_users list
		"""
        is_user_removed = False
        if user in self.connected_users.all():
            self.connected_users.remove(user)
            is_user_removed = True
        return is_user_removed

    def __str__(self):
        return f"A chat between {self.user1} and {self.user2}."

    @property
    def group_name(self):
        """
        Returns the Channels Group name that sockets should subscribe to get sent
        messages as they are generated.
        """
        return f"PrivateChatRoom-{self.id}"


class RoomChatMessageManager(models.Manager):
    def by_room(self, room):
        qs = RoomChatMessage.objects.filter(room=room).order_by("-timestamp")
        return qs


class RoomChatMessage(models.Model):
    """
    Chat message created by a user inside a Room
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField(unique=False, blank=False)

    objects = RoomChatMessageManager()

    def __str__(self):
        return self.content


class UnreadChatRoomMessages(models.Model):
    """
    Keep track of the number of unread messages by a specific user in a specific private chat.
    When the user connects the chat room, the messages will be considered "read" and 'count' will be set to 0.
    """
    room = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE, related_name="room")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    count = models.IntegerField(default=0)

    most_recent_message = models.CharField(max_length=500, blank=True, null=True)

    # last time msgs were read by the user
    reset_timestamp = models.DateTimeField()

    notifications = GenericRelation(Notification)

    def __str__(self):
        return f"Messages that {str(self.user.username)} has not read yet."

    def save(self, *args, **kwargs):
        if not self.id:  # if just created, add a timestamp. Otherwise do not automatically change it ever.
            self.reset_timestamp = timezone.now()
        return super(UnreadChatRoomMessages, self).save(*args, **kwargs)

    @property
    def get_cname(self):
        """
        For determining what kind of object is associated with a Notification
        """
        return "UnreadChatRoomMessages"

    @property
    def get_other_user(self):
        """
        Get the other user in the chat room
        """
        if self.user == self.room.user1:
            return self.room.user2
        else:
            return self.room.user1


@receiver(post_save, sender=PrivateChatRoom)
def create_unread_chatroom_messages_obj(sender, instance, created, **kwargs):
    if created:
        unread_msgs1 = UnreadChatRoomMessages(room=instance, user=instance.user1)
        unread_msgs1.save()

        unread_msgs2 = UnreadChatRoomMessages(room=instance, user=instance.user2)
        unread_msgs2.save()


@receiver(pre_save, sender=UnreadChatRoomMessages)
def increment_unread_msg_count(sender, instance, **kwargs):
    """
    When the unread message count increases, update the notification.
    If one does not exist, create one. (This should never happen)
    """
    if instance.id is None:  # new object will be created
        pass  # create_unread_chatroom_messages_obj will handle this scenario
    else:
        previous = UnreadChatRoomMessages.objects.get(id=instance.id)
        if previous.count < instance.count:  # if count is incremented
            content_type = ContentType.objects.get_for_model(instance)
            if instance.user == instance.room.user1:
                other_user = instance.room.user2
            else:
                other_user = instance.room.user1
            try:
                notification = Notification.objects.get(target=instance.user, content_type=content_type,
                                                        object_id=instance.id)
                notification.verb = instance.most_recent_message
                notification.timestamp = timezone.now()
                notification.save()
            except Notification.DoesNotExist:
                instance.notifications.create(
                    target=instance.user,
                    from_user=other_user,
                    redirect_url=f"{settings.BASE_DIR}/chat/?room_id={instance.room.id}",
                    # we want to go to the chatroom
                    verb=instance.most_recent_message,
                    content_type=content_type,
                )


@receiver(pre_save, sender=UnreadChatRoomMessages)
def remove_unread_msg_count_notification(sender, instance, **kwargs):
    """
    If the unread messge count decreases, it means the user joined the chat. So delete the notification.
    """
    if instance.id is None:  # new object will be created
        pass  # create_unread_chatroom_messages_obj will handle this scenario
    else:
        previous = UnreadChatRoomMessages.objects.get(id=instance.id)
        if previous.count > instance.count:  # if count is decremented
            content_type = ContentType.objects.get_for_model(instance)
            try:
                notification = Notification.objects.get(target=instance.user, content_type=content_type,
                                                        object_id=instance.id)
                notification.delete()
            except Notification.DoesNotExist:
                pass

templates/components/modal-error.html
<!-- Client Error MODAL -->
<div class="modal fade" id="id_client_error_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger" id="staticBackdropLabel">Socket Client Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="id_client_error_modal_body">
                Something went wrong.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-x-octagon">
                        <polygon
                                points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                        <line x1="15" y1="9" x2="9" y2="15"></line>
                        <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Client Error MODAL -->

templates/components/modal-profile.html
{% load static %}
<!-- Modal: Profile -->
<div class="modal fade" id="modal-profile" tabindex="-1" aria-labelledby="modal-profile" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-fullscreen-xl-down">
        <div class="modal-content">

            <!-- Modal body -->
            <div class="modal-body py-0">
                <!-- Header -->
                <div class="profile modal-gx-n">
                    <div class="profile-img text-primary rounded-top-xl">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 400 140.74">
                            <defs>
                                <style>.cls-2 {
                                    fill: #fff;
                                    opacity: 0.1;
                                }</style>
                            </defs>
                            <g>
                                <g>
                                    <path d="M400,125A1278.49,1278.49,0,0,1,0,125V0H400Z"/>
                                    <path class="cls-2"
                                          d="M361.13,128c.07.83.15,1.65.27,2.46h0Q380.73,128,400,125V87l-1,0a38,38,0,0,0-38,38c0,.86,0,1.71.09,2.55C361.11,127.72,361.12,127.88,361.13,128Z"/>
                                    <path class="cls-2"
                                          d="M12.14,119.53c.07.79.15,1.57.26,2.34v0c.13.84.28,1.66.46,2.48l.07.3c.18.8.39,1.59.62,2.37h0q33.09,4.88,66.36,8,.58-1,1.09-2l.09-.18a36.35,36.35,0,0,0,1.81-4.24l.08-.24q.33-.94.6-1.9l.12-.41a36.26,36.26,0,0,0,.91-4.42c0-.19,0-.37.07-.56q.11-.86.18-1.73c0-.21,0-.42,0-.63,0-.75.08-1.51.08-2.28a36.5,36.5,0,0,0-73,0c0,.83,0,1.64.09,2.45C12.1,119.15,12.12,119.34,12.14,119.53Z"/>
                                    <circle class="cls-2" cx="94.5" cy="57.5" r="22.5"/>
                                    <path class="cls-2" d="M276,0a43,43,0,0,0,43,43A43,43,0,0,0,362,0Z"/>
                                </g>
                            </g>
                        </svg>

                        <div class="position-absolute top-0 start-0 py-6 px-5">
                            <button type="button" class="btn-close btn-close-white btn-close-arrow opacity-100"
                                    data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                    </div>

                    <div class="profile-body">
                        <div class="avatar avatar-xl">
                            <img class="avatar-img" src="{{ user.profile_image.url }}" alt="">
                        </div>
                        {% if user.first_name and user.last_name %}
                            <h4 class="mb-1">{{ user.first_name }} {{ user.last_name }}</h4>
                        {% else %}
                            <h4 class="mb-1">{{ user.username }}</h4>
                        {% endif %}
                        {% if user.bio %}
                            <p>{{ user.bio }}</p>
                        {% endif %}
                    </div>
                </div>
                <!-- Header -->

                <hr class="hr-bold modal-gx-n my-0">

                <!-- List -->
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row align-items-center gx-6">
                            <div class="col">
                                <h5>Username</h5>
                                <p>{{ user.username }}</p>
                            </div>
                            <div class="col-auto">
                                <div class="btn btn-sm btn-icon btn-dark">
                                    <a class="text-reset" href="{% url 'account:view' user_id=request.user.id %}">

                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-user">
                                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                            <circle cx="12" cy="7" r="4"></circle>
                                        </svg>
                                    </a>
                                </div>
                            </div>


                        </div>
                    </li>

                    <li class="list-group-item">
                        <div class="row align-items-center gx-6">
                            <div class="col">
                                <h5>E-mail</h5>
                                <p>{{ user.email }}</p>
                            </div>

                            <div class="col-auto">
                                <div class="btn btn-sm btn-icon btn-dark">
                                    <a href="mailto:{{ user.email }}" class="text-reset">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-mail">
                                            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                                            <polyline points="22,6 12,13 2,6"></polyline>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>

                    {% if user.birth_date %}
                        <li class="list-group-item">
                            <div class="row align-items-center gx-6">
                                <div class="col">
                                    <h5>Birth Date</h5>
                                    <p>{{ user.birth_date|date:"m / d / Y" }}</p>
                                </div>
                                <div class="col-auto">
                                    <div class="btn btn-sm btn-icon btn-dark">
                                        <a href="https://www.google.com/calendar/event?action=TEMPLATE&dates={% now "Y" %}{{ birth_date|date:"md" }}T180000Z%2F20220406T190000Z&text={{ username }}'s%20Birthday&location=&details=Celebrate%20{{ username }}'s%20Birthday!!"
                                           target="_blank" class="text-reset">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                 height="24" viewBox="0 0 24 24" fill="none"
                                                 stroke="currentColor" stroke-width="2"
                                                 stroke-linecap="round" stroke-linejoin="round"
                                                 class="feather feather-calendar">
                                                <rect x="3" y="4" width="18" height="18" rx="2"
                                                      ry="2"></rect>
                                                <line x1="16" y1="2" x2="16" y2="6"></line>
                                                <line x1="8" y1="2" x2="8" y2="6"></line>
                                                <line x1="3" y1="10" x2="21" y2="10"></line>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endif %}


                </ul>
                <!-- List  -->

                <hr class="hr-bold modal-gx-n my-0">

                <!-- List -->
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row align-items-center gx-6">
                            <div class="col">
                                <h5>Dark Mode</h5>
                                <p>Activate Dark Mode.</p>
                            </div>

                            <div class="col-auto">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" id="id_dark_mode_toggle">
                                    <label class="form-check-label" for="id_dark_mode_toggle"></label>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <!-- List -->

                <hr class="hr-bold modal-gx-n my-0">

                <!-- List -->
                <ul class="list-group list-group-flush">
                    {% if user.is_superuser %}
                        <li class="list-group-item">
                            <a href="{% url 'admin:index' %}" class="text-reset" title="Admin Dashboard">Admin
                                Dashboard</a>
                        </li>
                    {% endif %}
                    <li class="list-group-item">
                        <a href="{% url 'account:edit' user_id=user.id %}" class="text-reset" title="Edit Profile">Edit
                            Profile</a>
                    </li>

                    <li class="list-group-item">
                        <a href="{% url 'logout' %}" class="text-danger">Logout</a>
                    </li>
                </ul>
                <!-- List -->
            </div>
            <!-- Modal body -->

        </div>
    </div>
</div>